package facade;
import facade.Restaurant;

import java.util.Random;

class PizzaXRestaurant implements Restaurant { // A concrete restaurant X.

    @Override
    public int createOrder() { // In this example, we define the order number by a random number generated by Java.

        Random rand = new Random(); // Internal call to generate a random number.
        int randomGenerated = rand.nextInt( Integer.MAX_VALUE ) + 1; // To generate only positive random numbers.
        return randomGenerated;
    }
    @Override
    public boolean isBakingDone() { // To simplify the example, we always return true.
        return true;
    }
}